/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.dao.HibernateUtil;
import br.com.senac.dao.UsuarioDao;
import br.com.senac.dao.UsuarioDaoImpl;
import br.com.senac.entidade.Usuario;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author ana.correa8
 */
public class AlteraSenha extends javax.swing.JFrame {

    /**
     * Creates new form AlterarSenha
     */
    private Usuario usuario;
    
    public AlteraSenha() {
        initComponents();
    }
    public AlteraSenha(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        varNome.setText(usuario.getNome());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_alteraSenha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        varNome = new javax.swing.JLabel();
        lb_senhaAntiga = new javax.swing.JLabel();
        lb_novaSenha = new javax.swing.JLabel();
        lb_confirmaSenha = new javax.swing.JLabel();
        varNovaSenha = new javax.swing.JPasswordField();
        varConfirmaSenha = new javax.swing.JPasswordField();
        varSenhaAntiga = new javax.swing.JPasswordField();
        btAltera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lb_alteraSenha.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lb_alteraSenha.setText("Altera Senha");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome: ");

        lb_senhaAntiga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_senhaAntiga.setText("Senha Antiga:");

        lb_novaSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_novaSenha.setText("Nova Senha:");

        lb_confirmaSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_confirmaSenha.setText("Confirma Senha:");

        varNovaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varNovaSenhaFocusLost(evt);
            }
        });

        varConfirmaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varConfirmaSenhaFocusLost(evt);
            }
        });

        varSenhaAntiga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varSenhaAntigaFocusLost(evt);
            }
        });

        btAltera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAltera.setText("Alterar");
        btAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlteraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btAltera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_senhaAntiga)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_novaSenha)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_alteraSenha)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(varSenhaAntiga, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(varConfirmaSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addComponent(varNovaSenha, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(varNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lb_alteraSenha)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_senhaAntiga)
                    .addComponent(varSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_novaSenha)
                    .addComponent(varNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_confirmaSenha)
                    .addComponent(varConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btAltera)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void varSenhaAntigaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varSenhaAntigaFocusLost
        // TODO add your handling code here:
        String senhaAntiga = String.valueOf(varSenhaAntiga.getPassword());
        if(!usuario.getSenha().equals(senhaAntiga)){
            JOptionPane.showMessageDialog(null, "Senha antiga não confere");
            varSenhaAntiga.grabFocus();
        }
    }//GEN-LAST:event_varSenhaAntigaFocusLost

    private void varNovaSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varNovaSenhaFocusLost
        // TODO add your handling code here:
        String novaSenha = String.valueOf(varNovaSenha.getPassword());
        if(usuario.getSenha().equals(novaSenha)){
            JOptionPane.showMessageDialog(null, "A nova senha não pode ser a mesma");
            varNovaSenha.grabFocus();
        }
    }//GEN-LAST:event_varNovaSenhaFocusLost

    private void varConfirmaSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varConfirmaSenhaFocusLost
        // TODO add your handling code here:
         String novaSenha = String.valueOf(varNovaSenha.getPassword());
         String confirmaSenha = String.valueOf(varConfirmaSenha.getPassword());
        if(novaSenha.equals(confirmaSenha)){
            JOptionPane.showMessageDialog(null, "As senhas não conferem");
            varConfirmaSenha.grabFocus();
        }
    }//GEN-LAST:event_varConfirmaSenhaFocusLost

    private void btAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlteraActionPerformed
        // TODO add your handling code here:
        if(validarFormulario()){
            UsuarioDao usuarioDao = new UsuarioDaoImpl();
            Session sessao = HibernateUtil.abrirConexao();
            String novaSenha = String.valueOf(varNovaSenha.getPassword());
            usuario.setSenha(novaSenha);
            try {
                usuarioDao.salvarOuAlterar(usuario, sessao);
                new Login().setVisible(true);
                dispose();
            } catch (HibernateException e) {
                System.out.println("Erro ao salvar senha" + e.getMessage());
                new TelaPrincipal(usuario).setVisible(true);
            }finally{
                sessao.close();
            }
        }
    }//GEN-LAST:event_btAlteraActionPerformed

     private boolean validarFormulario() {
        String senhaAntiga = String
                .valueOf(varSenhaAntiga.getPassword());
        if (validarCampoPreenchido(senhaAntiga)) {
            JOptionPane.showMessageDialog(null,
                    "Digite a senha antiga");
            return false;
        }

        String senhaNova = String
                .valueOf(varNovaSenha.getPassword());
        if (validarCampoPreenchido(senhaNova)) {
            JOptionPane.showMessageDialog(null,
                    "Digite a senha nova");
            return false;
        }

        String confirmaSenha = String
                .valueOf(varConfirmaSenha.getPassword());
        if (validarCampoPreenchido(confirmaSenha)) {
            JOptionPane.showMessageDialog(null,
                    "Digite um valor para confirma senha");
            return false;
        }
        return true;
    }

    private boolean validarCampoPreenchido(String campo) {
        return campo.length() < 3;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteraSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltera;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_alteraSenha;
    private javax.swing.JLabel lb_confirmaSenha;
    private javax.swing.JLabel lb_novaSenha;
    private javax.swing.JLabel lb_senhaAntiga;
    private javax.swing.JPasswordField varConfirmaSenha;
    private javax.swing.JLabel varNome;
    private javax.swing.JPasswordField varNovaSenha;
    private javax.swing.JPasswordField varSenhaAntiga;
    // End of variables declaration//GEN-END:variables
}
