/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.dao.ClienteDao;
import br.com.senac.dao.ClienteDaoImpl;
import br.com.senac.dao.HibernateUtil;
import br.com.senac.dao.ProfissaoDao;
import br.com.senac.dao.ProfissaoDaoImpl;
import br.com.senac.entidade.Cliente;
import br.com.senac.entidade.Endereco;
import br.com.senac.entidade.Profissao;
import br.com.senac.entidade.Telefone;
import br.com.senac.webService.CepRest;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author ana.correa8
 */
public class CadastroCliente extends javax.swing.JFrame {

    private ClienteDao clienteDao = new ClienteDaoImpl();
    private Session sessao;
    private Cliente cliente;
    private List<Profissao> profissoes;
    private Endereco endereco;

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        carregarComboProfissao();

    }

//    public CadastroCliente(CepRest cepRest) {
//        cepRest = new CepRest();
//
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        painel_01 = new javax.swing.JPanel();
        lb_nome = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        lb_cep = new javax.swing.JLabel();
        varBairro = new javax.swing.JTextField();
        lb_bairro = new javax.swing.JLabel();
        lb_profissao = new javax.swing.JLabel();
        varSalario = new javax.swing.JFormattedTextField();
        varCep = new javax.swing.JFormattedTextField();
        btBuscar = new javax.swing.JButton();
        lb_tipoTelefone = new javax.swing.JLabel();
        varTipoTelefone = new javax.swing.JComboBox<>();
        lb_salario1 = new javax.swing.JLabel();
        lb_localidade = new javax.swing.JLabel();
        varLocalidade = new javax.swing.JTextField();
        varComboProfissao = new javax.swing.JComboBox<>();
        varComplemento = new javax.swing.JTextField();
        lb_complemento1 = new javax.swing.JLabel();
        Painel_02 = new javax.swing.JPanel();
        varUf = new javax.swing.JTextField();
        lb_Uf = new javax.swing.JLabel();
        lb_cpf = new javax.swing.JLabel();
        varCpf = new javax.swing.JFormattedTextField();
        lb_telefone = new javax.swing.JLabel();
        varTelefone = new javax.swing.JFormattedTextField();
        lb_logradouro = new javax.swing.JLabel();
        varLogradouro = new javax.swing.JTextField();
        lb_numero = new javax.swing.JLabel();
        varNumero = new javax.swing.JTextField();
        lb_Rg = new javax.swing.JLabel();
        varRg = new javax.swing.JTextField();
        lb_operadora = new javax.swing.JLabel();
        varOperadora = new javax.swing.JComboBox<>();
        lb_observacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        varObservacao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        lb_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("Cadastro de Cliente");

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        lb_nome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_nome.setText("Nome:");

        lb_cep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_cep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_cep.setText("CEP: ");

        lb_bairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_bairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_bairro.setText("Bairro: ");

        lb_profissao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_profissao.setText("Profissão:");

        varSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        try {
            varCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        lb_tipoTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_tipoTelefone.setText("Tipo Telefone: ");

        varTipoTelefone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um tipo", "Fixo", "Celular" }));

        lb_salario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_salario1.setText("Salário: ");

        lb_localidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_localidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_localidade.setText("Localidade: ");

        varComboProfissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma profissão" }));

        lb_complemento1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_complemento1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_complemento1.setText("Complemento:");

        javax.swing.GroupLayout painel_01Layout = new javax.swing.GroupLayout(painel_01);
        painel_01.setLayout(painel_01Layout);
        painel_01Layout.setHorizontalGroup(
            painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_01Layout.createSequentialGroup()
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_01Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_localidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_01Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_01Layout.createSequentialGroup()
                                .addComponent(lb_profissao)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_01Layout.createSequentialGroup()
                                .addComponent(lb_tipoTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(varLocalidade)
                    .addGroup(painel_01Layout.createSequentialGroup()
                        .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painel_01Layout.createSequentialGroup()
                                    .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(varTipoTelefone, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                        .addComponent(varNome, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(varSalario, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(1, 1, 1))
                                .addComponent(varBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painel_01Layout.createSequentialGroup()
                                .addComponent(varCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(varComboProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(varComplemento, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_01Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(lb_salario1)
                    .addContainerGap(250, Short.MAX_VALUE)))
            .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_01Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(lb_complemento1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(250, Short.MAX_VALUE)))
        );
        painel_01Layout.setVerticalGroup(
            painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_01Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nome)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(varSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_profissao)
                    .addComponent(varComboProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tipoTelefone))
                .addGap(18, 18, 18)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_cep)
                    .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(varCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBuscar)))
                .addGap(18, 18, 18)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_bairro))
                .addGap(18, 18, 18)
                .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_localidade)
                    .addComponent(varLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(varComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painel_01Layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(lb_salario1)
                    .addContainerGap(346, Short.MAX_VALUE)))
            .addGroup(painel_01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_01Layout.createSequentialGroup()
                    .addContainerGap(328, Short.MAX_VALUE)
                    .addComponent(lb_complemento1)
                    .addGap(105, 105, 105)))
        );

        lb_Uf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_Uf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Uf.setText("UF: ");

        lb_cpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_cpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_cpf.setText("CPF: ");

        try {
            varCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lb_telefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_telefone.setText("Telefone: ");

        try {
            varTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lb_logradouro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_logradouro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_logradouro.setText("Logradouro: ");

        varLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varLogradouroActionPerformed(evt);
            }
        });

        lb_numero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_numero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_numero.setText("Número:");

        varNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNumeroActionPerformed(evt);
            }
        });

        lb_Rg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_Rg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Rg.setText("RG:");

        varRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varRgActionPerformed(evt);
            }
        });

        lb_operadora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_operadora.setText("Operadora:");

        varOperadora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma operadora", "Vivo", "Claro", "Tim", "Unifique", "Nextel", "Oi" }));

        lb_observacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_observacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_observacao.setText("Observação:");

        varObservacao.setColumns(20);
        varObservacao.setRows(5);
        jScrollPane1.setViewportView(varObservacao);

        javax.swing.GroupLayout Painel_02Layout = new javax.swing.GroupLayout(Painel_02);
        Painel_02.setLayout(Painel_02Layout);
        Painel_02Layout.setHorizontalGroup(
            Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_02Layout.createSequentialGroup()
                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Painel_02Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_02Layout.createSequentialGroup()
                                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_Uf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(varUf)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                            .addGroup(Painel_02Layout.createSequentialGroup()
                                .addComponent(lb_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(varLogradouro))
                            .addGroup(Painel_02Layout.createSequentialGroup()
                                .addComponent(lb_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(varNumero))))
                    .addGroup(Painel_02Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(varCpf))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel_02Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_telefone)
                            .addComponent(lb_Rg, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_operadora))
                        .addGap(10, 10, 10)
                        .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(varOperadora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(varTelefone)
                            .addComponent(varRg))))
                .addGap(32, 32, 32))
        );
        Painel_02Layout.setVerticalGroup(
            Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_02Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cpf)
                    .addComponent(varCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Rg)
                    .addComponent(varRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_telefone)
                    .addComponent(varTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_operadora)
                    .addComponent(varOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_logradouro)
                    .addComponent(varLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_numero)
                    .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Uf)
                    .addComponent(varUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(Painel_02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_observacao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Painel_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Painel_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varLogradouroActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_varLogradouroActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

       
        if (validarFormulario()) {
            carregarFormulario();
            try {
                sessao = HibernateUtil.abrirConexao();
                clienteDao.salvarOuAlterar(cliente, sessao);
                JOptionPane.showMessageDialog(null, "Cliente salvo com sucesso");
                dispose();
                new TelaPrincipal().setVisible(true);
            } catch (HibernateException e) {
                System.out.println("Erro ao salvar cliente");
            } finally {
                sessao.close();
            }
        }


    }//GEN-LAST:event_btSalvarActionPerformed
    private void carregarFormulario() {
        cliente = new Cliente();
        cliente.setNome(varNome.getText().trim());
        cliente.setCpf(varCpf.getText());
        cliente.setRg(varRg.getText().trim());
        //formatando salario
        String valorSalario = varSalario.getText().trim();
        valorSalario = valorSalario.replace(".", ",");
        valorSalario = valorSalario.replace(",", ".");//troca a vírgula por ponto ou qualquer outra informação desejada
        double salario = Double.valueOf(valorSalario);
        cliente.setSalario(salario);

        //telefone
        Telefone telefone = new Telefone();
        telefone.setTipo(varTipoTelefone.getSelectedItem().toString());
        telefone.setOperadora(varOperadora.getSelectedItem().toString());
        telefone.setDdd(varTelefone.getText().substring(0, 4));
        telefone.setNumero(varTelefone.getText().substring(4));
        
        cliente.setTelefone(telefone);
        
        //endereco
        if(endereco.getLogradouro()!= null){
            endereco.setNumero(varNumero.getText().trim());
            endereco.setComplemento(varComplemento.getText().trim());
            endereco.setObservacao(varObservacao.getText().trim());
        }else{
            endereco.setLogradouro(varLogradouro.getText().trim());
            endereco.setLocalidade(varLocalidade.getText().trim());
            endereco.setUf(varUf.getText().trim());
            endereco.setBairro(varBairro.getText().trim());
        }
        cliente.setEndereco(endereco);
        
       

    }
    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        String cep = varCep.getText();
        if (cep.length() == 9) {
            CepRest cepRest = new CepRest();
             endereco = cepRest.pesquisarCep(cep);
            if (endereco.getLogradouro() == null) {
                JOptionPane.showMessageDialog(null, "Digite um CEP válido");

            } else {
                varLogradouro.setText(endereco.getLogradouro());
                varLocalidade.setText(endereco.getLocalidade());
                varBairro.setText(endereco.getBairro());
                varUf.setText(endereco.getUf());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite um CEP válido");

        }
    }//GEN-LAST:event_btBuscarActionPerformed
    private boolean validarFormulario() {
        String nome = varNome.getText().trim();
        if (validarMenorQue3(nome)) {
            JOptionPane.showMessageDialog(null, "Digite um nome com mais de três caracteres");
            return false;

        }

        String tel = varTelefone.getText().trim();
        if (tel.length() < 14) {
            JOptionPane.showMessageDialog(null, "Digite um telefone válido");
        } else {
            String ddd = varTelefone.getText().substring(0, 4); // primeiro é o índice e o segundo é o elemento ou seja, na vida real(índice do fim + 1)
            String numeroTel = varTelefone.getText().substring(4);
            return true;
        }

        String tipo = varTipoTelefone.getSelectedItem().toString();
        if (varTipoTelefone.equals("Escolha um tipo")) {
            JOptionPane.showMessageDialog(null, "Escolha um tipo de telefone");
            return false;
        }
        String cpf = varCpf.getText().trim();
        if (cpf.length() < 14) {
            JOptionPane.showMessageDialog(null, "Digite um CPF correto");
            return false;
        }
        String valorSalario = varSalario.getText().trim();
        if (valorSalario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo salário não pode estar em branco");
            return false;
        }
        String convertido = valorSalario.replace(",", "."); //troca a vírgula por ponto ou qualquer outra informação desejada
        double salario = Double.valueOf(convertido);

        if (salario < 0) {
            JOptionPane.showMessageDialog(null, "Digite um salário maior que zero");
            return false;
        }
        String rg = varRg.getText().trim();
        if (validarMenorQue3(rg)) {
            JOptionPane.showMessageDialog(null, "Digite RG corretamene");
            return false;
        }
        if (varOperadora.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Escolha uma operdora");
            return false;

        }
        if (varComboProfissao.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Escolha uma profissão");
            return false;
        }
        String cep = varCep.getText().trim();
        if (cep.length() < 9) {
            JOptionPane.showMessageDialog(null, "Preencha o CEP corretamente");
            return false;
        }
        String logradouro = varLogradouro.getText().trim();
        if (validarMenorQue3(logradouro)) {
            JOptionPane.showMessageDialog(null, "Digite o logradouro corretamente");
            return false;
        }
        String bairro = varBairro.getText().trim();
        if (validarMenorQue3(bairro)) {
            JOptionPane.showMessageDialog(null, "Digite o Bairro corretamente");
            return false;
        }
        String cidade = varLocalidade.getText().trim();
        if (validarMenorQue3(cidade)) {
            JOptionPane.showMessageDialog(null, "Digite a Cidade corretamente");
            return false;
        }
        String estado = varUf.getText().trim();
        if (estado.length() != 2) {
            JOptionPane.showMessageDialog(null, "Digite a sigla do Estado");
            return false;
        }

        String numero = varNumero.getText().trim();
        if (numero.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite um número para o logradouro");
            return false;
        }
        String complemento = varComplemento.getText().trim();
        if (validarMenorQue3(complemento)) {
            JOptionPane.showMessageDialog(null, "Digite um complemento corretamente");
            return false;
        }

        return true;
    }

    private boolean validarMenorQue3(String valor) {
        return valor.length() < 3;

    }

    private void carregarComboProfissao() {
        ProfissaoDao profissaoDao = new ProfissaoDaoImpl();
        try {
            sessao = HibernateUtil.abrirConexao();
            profissoes = profissaoDao.pesquisarTodos(sessao);

            profissoes.forEach(profissao -> {
                varComboProfissao.addItem(profissao.getNome());
            });

        } catch (HibernateException e) {
            System.out.println("Erro ao pesquisar profissão" + e.getMessage());
        } finally {
            sessao.close();
        }
    }
    private void varNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNumeroActionPerformed

    private void varRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varRgActionPerformed

//    private void validarSalario() {
//        String valorSalario = varSalario.getText();
//        if (valorSalario.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Digite um salário maior que zero");
//        } else {
//            String convertido = valorSalario.replace(",", "."); //troca a vírgula por ponto ou qualquer outra informação desejada
//            cliente.setSalario(Double.valueOf(convertido));
//        }
//    }
//    private void validarCpf() {
//        String cpf = varCpf.getText().trim();
//     private void validarTelefone(){
//         String tel = varTelefone.getText().trim();
//         if(tel.length()<14){
//             JOptionPane.showMessageDialog(null, "Digite um telefone válido");
//         }else{
//             String ddd = varTelefone.getText().substring(0, 4); // primeiro é o índice e o segundo é o elemento ou seja, na vida real(índice do fim + 1)
//             String numeroTel = varTelefone.getText().substring(4);
//         }
//       
//    }
    private void validarTipoTelefone() {
        String tipo = varTipoTelefone.getSelectedItem().toString();
        if (varTipoTelefone.equals("Escolha um tipo")) {
            JOptionPane.showMessageDialog(null, "Escolha um tipo de telefone");
        } else {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_02;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Rg;
    private javax.swing.JLabel lb_Uf;
    private javax.swing.JLabel lb_bairro;
    private javax.swing.JLabel lb_cep;
    private javax.swing.JLabel lb_complemento1;
    private javax.swing.JLabel lb_cpf;
    private javax.swing.JLabel lb_localidade;
    private javax.swing.JLabel lb_logradouro;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_numero;
    private javax.swing.JLabel lb_observacao;
    private javax.swing.JLabel lb_operadora;
    private javax.swing.JLabel lb_profissao;
    private javax.swing.JLabel lb_salario1;
    private javax.swing.JLabel lb_telefone;
    private javax.swing.JLabel lb_tipoTelefone;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JPanel painel_01;
    private javax.swing.JTextField varBairro;
    private javax.swing.JFormattedTextField varCep;
    private javax.swing.JComboBox<String> varComboProfissao;
    private javax.swing.JTextField varComplemento;
    private javax.swing.JFormattedTextField varCpf;
    private javax.swing.JTextField varLocalidade;
    private javax.swing.JTextField varLogradouro;
    private javax.swing.JTextField varNome;
    private javax.swing.JTextField varNumero;
    private javax.swing.JTextArea varObservacao;
    private javax.swing.JComboBox<String> varOperadora;
    private javax.swing.JTextField varRg;
    private javax.swing.JFormattedTextField varSalario;
    private javax.swing.JFormattedTextField varTelefone;
    private javax.swing.JComboBox<String> varTipoTelefone;
    private javax.swing.JTextField varUf;
    // End of variables declaration//GEN-END:variables

}
