/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.dao.HibernateUtil;
import br.com.senac.dao.ProfissaoDao;
import br.com.senac.dao.ProfissaoDaoImpl;
import br.com.senac.entidade.Profissao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author ana.correa8
 */
public class PesquisarProfissao extends javax.swing.JFrame {

    private Session sessao;
    private ProfissaoDao profissaoDao;
    private Profissao profissao;
    private List<Profissao> profissoes;

    /**
     * Creates new form PesquisarProfissao
     */
    public PesquisarProfissao() {
        initComponents();
        profissaoDao = new ProfissaoDaoImpl();
        btAtivo_Inativo.setVisible(false);
        //verificarSituacao();
    }

    private void verificarSituacao() {
        if(profissao.isSituacao()){
            btAtivo_Inativo.setText("Desativar");
            
        }else{
            btAtivo_Inativo.setText("Ativar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Profissao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProfissao = new javax.swing.JTable();
        btAlterar = new javax.swing.JButton();
        btAtivo_Inativo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisar Profissão");

        lb_Profissao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_Profissao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Profissao.setText("Pesquisar Profissão");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome: ");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        tbProfissao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Situação"
            }
        ));
        jScrollPane1.setViewportView(tbProfissao);

        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btAtivo_Inativo.setText("Ativar");
        btAtivo_Inativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtivo_InativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Profissao, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAtivo_Inativo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lb_Profissao)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlterar)
                    .addComponent(btAtivo_Inativo))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        String nome = varNome.getText().trim();
         btAtivo_Inativo.setEnabled(true);
        if (nome.length() < 2) {
            JOptionPane.showMessageDialog(null, "Digite para a profissão um nome com mais de dois caracteres");

        }else{
            try {
                sessao = HibernateUtil.abrirConexao();
                profissoes = profissaoDao.pesquisarPorNome(nome, sessao);
                if(profissoes.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Nenhuma profissão encontrada");
                }else{
                    carregarTabelaProfissao(profissoes);
                }
            } catch (HibernateException  e) {
                System.out.println("Erro ao pesquisar profissão" + e.getMessage());
            }finally{
                sessao.close();
            }
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tbProfissao.getSelectedRow();
         if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione uma profissão para alterar");
        }else{
              
               new CadastroProfissao(profissao).setVisible(true);
               dispose();
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btAtivo_InativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtivo_InativoActionPerformed
        // TODO add your handling code here:
        int linhaselecionada = tbProfissao.getSelectedRow();
        if(linhaselecionada < 0){
            JOptionPane.showMessageDialog(null, "Profissão excluída com sucesso! ");
        }else{
            try {
                sessao = HibernateUtil.abrirConexao();
                profissao = profissoes.get(linhaselecionada);
                profissaoDao.excluir(profissao, sessao);
                
                profissao.setSituacao(false);
               
                dispose();
                JOptionPane.showMessageDialog(null, "Profissão desativada com sucesso! ");
            } catch (HibernateException e) {
                System.out.println("Erro ao excluir profissão" + e.getMessage());
            }finally{
                sessao.close();
            }
        }
    }//GEN-LAST:event_btAtivo_InativoActionPerformed
    private void ativarOuInativarProfissao(){
        
        if(btAtivo_Inativo.getText().equals("Ativo")){
            btAtivo_Inativo.setText("Inativo");
            
        }else{
            btAtivo_Inativo.setText("Ativo");
        }
    }
   
    private void carregarTabelaProfissao(List<Profissao> profissaos) {
        DefaultTableModel defaultTable = (DefaultTableModel) tbProfissao.getModel();
        defaultTable.setNumRows(0); //limpa a tabela
        profissaos.stream().forEach(per -> {
            defaultTable.addRow(new Object[]{per.getNome(), per.getDescricao()});
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarProfissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarProfissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarProfissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarProfissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarProfissao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btAtivo_Inativo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Profissao;
    private javax.swing.JTable tbProfissao;
    private javax.swing.JTextField varNome;
    // End of variables declaration//GEN-END:variables
}
